// Script for parsing colors from colors.styl and generating themes.ts
const fs = require('fs');
const path = require('path');

const stylusPath = path.join(__dirname, '../src/styles/colors.styl');
const outputPath = path.join(__dirname, '../src/constants/themes.ts');

// Regex patterns
const ROOT_REGEX = /^:root\n((?:[ ]{2,}.+\n)+)/gm;
const THEME_REGEX = /^(\.[\w-]+)\n((?:[ ]{2,}.+\n)+)/gm;
const VAR_REGEX = /--([\w-]+)\s+([^\n]+)/g;

// MAIN EXECUTION:
try {
  const stylus = fs.readFileSync(stylusPath, 'utf8').replace(/\r\n/g, '\n');
  
  const commonVars = extractCommonVariables(stylus);
  const themes = extractThemes(stylus, commonVars);

  /**
   * Convert themes object to TypeScript string
   * @param {Object} themes - Themes object
   * @returns {string} TypeScript object string
   */
  function toObjectString(themes) {
    return (
      '{\n' +
      Object.entries(themes)
        .map(
          ([themeName, vars]) =>
            `  ${themeName}: {\n` +
            Object.entries(vars)
              .map(([key, value]) => `    ${key}: '${value}',`)
              .join('\n') +
            '\n  },'
        )
        .join('\n') +
      '\n}'
    );
  }

  const fileContent = `// This file is auto-generated by scripts/js-themes.cjs. Do not edit manually.
export const THEMES = ${toObjectString(themes)} as const;
`;

  fs.writeFileSync(outputPath, fileContent);
  console.log('✅ themeColors.ts generated successfully!');
  
} catch (error) {
  console.error('❌ Error generating themes:', error.message);
  process.exit(1);
}

// UTILS:

/**
 * Convert kebab-case to camelCase
 * @param {string} str - String in kebab-case
 * @returns {string} String in camelCase
 */
function toCamelCase(str) {
  return str
    .replace(/-color$/, '') // Remove '-color' ending
    .replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase()); // Convert to camelCase
}

/**
 * Extract variables from a CSS block
 * @param {string} block - CSS block content
 * @returns {Object} Object with camelCase keys and CSS values
 */
function extractVariables(block) {
  const vars = {};
  let match;
  
  while ((match = VAR_REGEX.exec(block)) !== null) {
    const rawKey = match[1];
    const key = toCamelCase(rawKey);
    vars[key] = match[2].trim();
  }
  
  return vars;
}

/**
 * Extract common variables from :root block
 * @param {string} stylus - Stylus file content
 * @returns {Object} Common variables
 */
function extractCommonVariables(stylus) {
  const rootMatch = ROOT_REGEX.exec(stylus);
  return rootMatch ? extractVariables(rootMatch[1]) : {};
}

/**
 * Extract theme variables from theme blocks
 * @param {string} stylus - Stylus file content
 * @param {Object} commonVars - Common variables to include in each theme
 * @returns {Object} Theme objects
 */
function extractThemes(stylus, commonVars) {
  const themes = {};
  let match;

  while ((match = THEME_REGEX.exec(stylus)) !== null) {
    const themeName = match[1].replace('.', '').replace('-theme', '').toLowerCase();
    const varsBlock = match[2];
    
    // Start with common variables and override with theme-specific ones
    const themeVars = { ...commonVars, ...extractVariables(varsBlock) };
    themes[themeName] = themeVars;
  }

  return themes;
}